// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8vRByIGkZepmPMeUJhR-fIHffB9_Kw7E',
    appId: '1:619828801275:web:7ed93de0a47777487a4a5e',
    messagingSenderId: '619828801275',
    projectId: 'tourbuddyapp-7dd7e',
    authDomain: 'tourbuddyapp-7dd7e.firebaseapp.com',
    storageBucket: 'tourbuddyapp-7dd7e.firebasestorage.app',
    measurementId: 'G-PWGX67W6WF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqXR2e8FUZ8KnFZ7Yi5C-UXXfW3tmbQhc',
    appId: '1:619828801275:android:c79a7c3ba0e2f10a7a4a5e',
    messagingSenderId: '619828801275',
    projectId: 'tourbuddyapp-7dd7e',
    storageBucket: 'tourbuddyapp-7dd7e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnVTXkYlXv-lwein_BqTbNVfthcPhNvo0',
    appId: '1:619828801275:ios:a90414194cca5e907a4a5e',
    messagingSenderId: '619828801275',
    projectId: 'tourbuddyapp-7dd7e',
    storageBucket: 'tourbuddyapp-7dd7e.firebasestorage.app',
    iosBundleId: 'com.example.tourBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnVTXkYlXv-lwein_BqTbNVfthcPhNvo0',
    appId: '1:619828801275:ios:a90414194cca5e907a4a5e',
    messagingSenderId: '619828801275',
    projectId: 'tourbuddyapp-7dd7e',
    storageBucket: 'tourbuddyapp-7dd7e.firebasestorage.app',
    iosBundleId: 'com.example.tourBuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8vRByIGkZepmPMeUJhR-fIHffB9_Kw7E',
    appId: '1:619828801275:web:2cccc745cb61835e7a4a5e',
    messagingSenderId: '619828801275',
    projectId: 'tourbuddyapp-7dd7e',
    authDomain: 'tourbuddyapp-7dd7e.firebaseapp.com',
    storageBucket: 'tourbuddyapp-7dd7e.firebasestorage.app',
    measurementId: 'G-WTVD3K3Q7S',
  );
}
